/*
 * pdfutils.h
 * Copyright (C) 2014 tox <tox@rootkit>
 *
 * Distributed under terms of the MIT license.
 */

#ifndef PDFUTILS_H
#define PDFUTILS_H

enum PageLayout {
	PAGE_LAYOUT_UNSET,
	PAGE_LAYOUT_SINGLE_PAGE,
	PAGE_LAYOUT_ONE_COLUMN,
	PAGE_LAYOUT_TWO_COLUMN_LEFT,
	PAGE_LAYOUT_TWO_COLUMN_RIGHT,
	PAGE_LAYOUT_TWO_PAGE_LEFT,
	PAGE_LAYOUT_TWO_PAGE_RIGHT
};

enum PageMode {
	PAGE_MODE_UNSET,
	PAGE_MODE_NONE,
	PAGE_MODE_USE_OUTLINES,
	PAGE_MODE_USE_THUMBS,
	PAGE_MODE_FULL_SCREEN,
	PAGE_MODE_USE_OC,
	PAGE_MODE_USE_ATTACHMENTS
};

enum Permission {
	PERMISSIONS_PRINT = 1 << 0,
	PERMISSIONS_MODIFY = 1 << 1,
	PERMISSIONS_COPY = 1 << 2,
	PERMISSIONS_ADD_NOTES = 1 << 3,
	PERMISSIONS_FILL_FORM = 1 << 4,
	PERMISSIONS_EXTRACT_CONTENTS = 1 << 5,
	PERMISSIONS_ASSEMBLE = 1 << 6,
	PERMISSIONS_PRINT_HIGH_RESOLUTION = 1 << 7,
	PERMISSIONS_FULL = (1 << 8) - 1
};

#endif /* !PDFUTILS_H */
